### ISSUE TITLE
Fluffychat on linux phone fails to launch

### ISSUE THREAD

**Issue by wisemonkey** [flathub/im.fluffychat.Fluffychat#83]
With following error:
`flatpak run im.fluffychat.Fluffychat

** (fluffychat:2): CRITICAL **: 19:14:48.203: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (fluffychat:2): CRITICAL **: 19:14:48.215: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method SystemTheme.accentColor on channel system_theme)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
<asynchronous suspension>
#1      SystemAccentColor.load (package:system_theme/system_theme.dart:86)
<asynchronous suspension>

No provider of glFenceSync found.  Requires one of:
    Desktop OpenGL 3.2
    GL_ARB_sync
    OpenGL ES 3.0
    GL_APPLE_sync`

**Comment by 1peter10** [comment]
Which hardware do you use?
It looks like that your hardware does not support OpenGL ES 3.0 in hardware (e.g., ARM Mali 400 GPU in PinePhone) or software (Vivante GC7000Lite in Librem 5). Since the requirement is a requirement in Flutter, not Fluffychat, there's next to nothing Fluffychat developers can do about this.
You can get Fluffychat to work by disabling GPU support, see https://linuxphoneapps.org/apps/im.fluffychat.fluffychat/#notice for one way to do so.
